//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-146 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.03.05 at 02:52:09 PM ICT 
//


package com.temenos.tws.pojo.FUNDSTRANSFERVMBACTREB;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.temenos.tws.pojo.FUNDSTRANSFERVMBACTREB package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Row_QNAME = new QName("", "row");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.temenos.tws.pojo.FUNDSTRANSFERVMBACTREB
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GDELIVERYOUTREF }
     * 
     */
    public GDELIVERYOUTREF createGDELIVERYOUTREF() {
        return new GDELIVERYOUTREF();
    }

    /**
     * Create an instance of {@link MCOMMISSIONTYPE }
     * 
     */
    public MCOMMISSIONTYPE createMCOMMISSIONTYPE() {
        return new MCOMMISSIONTYPE();
    }

    /**
     * Create an instance of {@link GCOMMISSIONTYPE }
     * 
     */
    public GCOMMISSIONTYPE createGCOMMISSIONTYPE() {
        return new GCOMMISSIONTYPE();
    }

    /**
     * Create an instance of {@link GORDERINGCUST }
     * 
     */
    public GORDERINGCUST createGORDERINGCUST() {
        return new GORDERINGCUST();
    }

    /**
     * Create an instance of {@link GOVERRIDE }
     * 
     */
    public GOVERRIDE createGOVERRIDE() {
        return new GOVERRIDE();
    }

    /**
     * Create an instance of {@link FUNDSTRANSFERVMBACTREBType }
     * 
     */
    public FUNDSTRANSFERVMBACTREBType createFUNDSTRANSFERVMBACTREBType() {
        return new FUNDSTRANSFERVMBACTREBType();
    }

    /**
     * Create an instance of {@link GPAYMENTDETAILS }
     * 
     */
    public GPAYMENTDETAILS createGPAYMENTDETAILS() {
        return new GPAYMENTDETAILS();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FUNDSTRANSFERVMBACTREBType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "row")
    public JAXBElement<FUNDSTRANSFERVMBACTREBType> createRow(FUNDSTRANSFERVMBACTREBType value) {
        return new JAXBElement<FUNDSTRANSFERVMBACTREBType>(_Row_QNAME, FUNDSTRANSFERVMBACTREBType.class, null, value);
    }

}
